CREATE DATABASE IF NOT EXISTS bai6;
USE bai6;

CREATE TABLE BOOK (
    BookID CHAR(5) PRIMARY KEY,
    BookName VARCHAR(200) NOT NULL,
    Quantity INT NOT NULL CHECK (Quantity >= 0),
    RentalPrice DECIMAL(10,2) NOT NULL DEFAULT 5000,
    ImportDate DATE
);

CREATE TABLE BORROW_BOOKS (
    BorrowID INT AUTO_INCREMENT PRIMARY KEY,
    BookID CHAR(5) NOT NULL,
    BorrowDate DATE DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (BookID) REFERENCES BOOK(BookID)
);